CREATE TABLE TOPIC(
  TOPICID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  CATEGORYID INTEGER NOT NULL REFERENCES CATEGORY(CATEGORYID),
  CONTENT VARCHAR(5000) NOT NULL,
  USERID INTEGER NOT NULL REFERENCES PROFILE(USERID),
  DATECREATED DATE NOT NULL,
  TIMECREATED TIMESTAMP,
  DATEUPDATED DATE NOT NULL,
  TIMEUPDATED TIMESTAMP,
  CUSTOM VARCHAR(10000),
  PRIMARY KEY (TOPICID)
);