CREATE TABLE RATING_ASSOC(
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  USERID INTEGER NOT NULL REFERENCES PROFILE(USERID),
  POSTID INTEGER NOT NULL REFERENCES POST(POSTID),
  UPVOTE BOOLEAN NOT NULL,
  UNIQUE(USERID, POSTID)
);